### ISSUE TITLE
Extension pop-up size issue

### ISSUE THREAD

**Issue by bestpika** [lockerpm/extension#1]
First, the screenshot:
![image](https://github.com/lockerpm/extension/assets/5698157/8f2e6020-364f-4821-b2cd-1bc48ddb7d7e)

Windows | 10 x64
Chrome | 116.0.5845.82 beta x64

**Comment by luongnh261** [comment]
Hi Bestpika, we are sorry for your bad experience. We have been aware of this issue and are working on it. This will be fixed in the next updated version.

**Comment by luongnh261** [comment]
@bestpika what is the version number of the Locker Extension you are facing the issue with? And could you please perform the function again and provide us with a video, or let us know the steps to reproduce the bug?

**Comment by bestpika** [comment]
@luongnh261 Sorry, I forgot to fill in the extension version (I installed it today).
The version I installed is v3.0.14.
My steps are to go to the Chrome Web Store and install the extension, then click on the extension icon, there are no other steps.

**Comment by bestpika** [comment]
This issue is obviously caused by the width problem of the extension’s pop-up.
![image](https://github.com/lockerpm/extension/assets/5698157/5807dbaa-62dd-4151-8fe0-b42638e78136)

**Comment by bestpika** [comment]
https://github.com/lockerpm/extension/blob/f6241a2ee65726ca477376f40b2037b6d8b95421/src/assets/app.scss#L30
Maybe we should add a `min-width: 400px;` here.

**Comment by bestpika** [comment]
Okay, I found that v3.0.15 fixed this issue.
Also, I just saw on the Chrome web store that there is a [Staging] Locker - Password Manager.
So should I just install that instead?
The result is that your another extension has not fixed this issue yet.

**Comment by everping** [comment]
Hi @bestpika,

Yes, we fixed your issue on the extension version 3.0.15.

The `[Staging] Locker - Password Manager` is just for our dev and testing team, you should ignore that.
